# Generated by Django 3.0.6 on 2020-05-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpanishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishSpanishTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_words', to='dictionaries.EnglishWord')),
                ('es_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_words', to='dictionaries.SpanishWord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='englishspanishtranslation',
            constraint=models.UniqueConstraint(fields=('en_word', 'es_word'), name='unique_translation'),
        ),
    ]
