# Generated by Django 3.0.6 on 2020-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(db_index=True, max_length=40)),
                ('es_word', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'unique_together': {('en_word', 'es_word')},
            },
        ),
    ]
